export const FETCH_ALL_USERS_DATA = 'FETCH_ALL_USERS_DATA';
export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_SIGNOUT = 'USER_AUTH_SIGNOUT';
